version: '3.8'

services:
  server:
    build: ./server
    container_name: server_backend-1
    ports:
      - '4000:5000'  # Map host port 4000 to container port 5000 (Flask default)
    volumes:
      - ./server:/app
      - ./nifty-yeti-429817-d1-5ab9ebaadbe3.json:/app/nifty-yeti-429817-d1-5ab9ebaadbe3.json
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/nifty-yeti-429817-d1-5ab9ebaadbe3.json

  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules:/app/node_modules
    stdin_open: true
    tty: true
