services:
  server:
    build: ./server
    container_name: server_backend
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules:/app/node_modules
    stdin_open: true
    tty: true