services:
  server:
    build: ./server
    container_name: server_backend-1
    ports:
      - '4000:5000'  # Map host port 4000 to container port 5000 (Flask default)
    volumes:
      - ./server:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules:/app/node_modules
    stdin_open: true
    tty: true