version: '3.8'

services:
  server_backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/nifty-yeti-429817-d1-5ab9ebaadbe3.json
    volumes:
      - ./nifty-yeti-429817-d1-5ab9ebaadbe3.json:/app/nifty-yeti-429817-d1-5ab9ebaadbe3.json
      - ./static:/app/static
      - ./templates:/app/templates
